# fly.toml app configuration file generated for cinematoday on 2023-04-21T21:36:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinematoday"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
